### ISSUE TITLE
Petobens name fixed

### ISSUE THREAD

**Issue by andrebrener** [petobens/dotfiles#15]
Give the option to change this name.

<img width="1435" alt="screen shot 2017-12-07 at 10 19 22 am" src="https://user-images.githubusercontent.com/14171845/33717321-3bf753f4-db38-11e7-917d-62f73bf054fe.png">

And also the same with the vim snippet

**Comment by petobens** [comment]
Fixed here (tmux): https://github.com/petobens/dotfiles/commit/1779cdbd6bf37f18c403f7dbf15eea155169bc3a and here (snippets): https://github.com/petobens/dotfiles/commit/f20a42b47190caa3518df256c92e8add9105b472
