### ISSUE TITLE
reusage of &errorformat of chktex

### ISSUE THREAD

**Issue by Konfekt** [petobens/dotfiles#20]
Dear @petobens

I [reused](https://github.com/Konfekt/vim-compilers/commit/51880e377c2b1892f9f14181e6062366cdaf6faf) your [definition of `&errorformat` for `chktex`](https://github.com/petobens/dotfiles/blob/02a3307c5ab48fd57545043600968656e69433e5/vim/ftplugin/tex/latex_settings.vim#L324)

I hope this is in accordance with any copyright laws (not spotted by me) that apply to this repo after [adding your MIT license header](https://github.com/Konfekt/vim-compilers/commit/7f9062091a5eb9f2a4386137f377931053a79948)?

**Comment by Konfekt** [comment]
Would you mind using it in [vimtex](https://github.com/lervag/vimtex/blob/e6c03a17611a71ab1fc12ed0e9b4c32bf9ca826b/compiler/chktex.vim) as well? That is, a pull request [updating it](https://github.com/Konfekt/vim-compilers/blob/bef300e8a0bee098256a6f91ad8c3ee053b2d509/compiler/chktex.vim)?

**Comment by petobens** [comment]
Fine by me!
