### ISSUE TITLE
Tmux Tree session_id pattern match can match multiple sessions

### ISSUE THREAD

**Issue by skeletony007** [petobens/dotfiles#22]
### Issue

https://github.com/petobens/dotfiles/blob/b951173d727fdbf843119966173586a075347c60/config/tmux/tmux_tree#L4-L5

The bash script [`tmux_tree`](https://github.com/petobens/dotfiles/blob/b951173d727fdbf843119966173586a075347c60/config/tmux/tmux_tree) has an issue where any `session_id`s starting with the same characters are included (by `grep`) in `session_info`.

### Example

Session ids `$1` and `$10` might give `session_info` for session `$1` like

```
0<session-ten-name>: 2 windows (attached)
$1<session-one-name>: 1 windows
```

which is echoed in the output.

### Recommended fix

Add a space after the session id in the format

```bash
S=$(tmux ls -F'#{session_id} #{session_name}: #{T:tree_mode_format}' | grep ^"$s ")
session_info=${S##$s }
```

This fixes the issue by making sure that the `session_name` and the `session_id` are properly separated

There is also an unnecessary check

https://github.com/petobens/dotfiles/blob/b951173d727fdbf843119966173586a075347c60/config/tmux/tmux_tree#L7

This could just be

```bash
if [[ "$1" == "$session_name" ]]; then
```

**Comment by petobens** [comment]
Thanks! Can you make a pr?
